// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0sHYGo_UHLuxzmYk_J5z5Uhn_gCNFeOc',
    appId: '1:876440892223:web:55dc76e956be7faf4e598a',
    messagingSenderId: '876440892223',
    projectId: 'app-chat-8e463',
    authDomain: 'app-chat-8e463.firebaseapp.com',
    storageBucket: 'app-chat-8e463.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl6tITqwAmDQn3EFrXw5aqUhO2gJkP6NM',
    appId: '1:876440892223:android:ea099450a2eb741f4e598a',
    messagingSenderId: '876440892223',
    projectId: 'app-chat-8e463',
    storageBucket: 'app-chat-8e463.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0sHYGo_UHLuxzmYk_J5z5Uhn_gCNFeOc',
    appId: '1:876440892223:web:092fd48a25fe529f4e598a',
    messagingSenderId: '876440892223',
    projectId: 'app-chat-8e463',
    authDomain: 'app-chat-8e463.firebaseapp.com',
    storageBucket: 'app-chat-8e463.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRYdCaNUw5iG33PsBo2YygNdQQBuWENz8',
    appId: '1:876440892223:ios:b5cf67a3080bbb044e598a',
    messagingSenderId: '876440892223',
    projectId: 'app-chat-8e463',
    storageBucket: 'app-chat-8e463.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRYdCaNUw5iG33PsBo2YygNdQQBuWENz8',
    appId: '1:876440892223:ios:b5cf67a3080bbb044e598a',
    messagingSenderId: '876440892223',
    projectId: 'app-chat-8e463',
    storageBucket: 'app-chat-8e463.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

}